"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecurityCameraIcon = exports.RoboticArmIcon = exports.SmartPlugIcon = exports.LightBulbIcon = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const LightBulbIcon = ({ className }) => ((0, jsx_runtime_1.jsx)("div", { className: `relative ${className}`, children: (0, jsx_runtime_1.jsx)("div", { className: "w-24 h-24 bg-[#FFC22E] border-4 border-black rounded-full flex items-center justify-center shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-transform hover:scale-110", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Lightbulb, { size: 48, strokeWidth: 2.5, color: "black" }) }) }));
exports.LightBulbIcon = LightBulbIcon;
const SmartPlugIcon = ({ className }) => ((0, jsx_runtime_1.jsx)("div", { className: `relative ${className}`, children: (0, jsx_runtime_1.jsx)("div", { className: "w-24 h-24 bg-[#29A873] border-4 border-black rounded-2xl flex items-center justify-center shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-transform hover:scale-110", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Plug, { size: 48, strokeWidth: 2.5, color: "black" }) }) }));
exports.SmartPlugIcon = SmartPlugIcon;
const RoboticArmIcon = ({ className }) => ((0, jsx_runtime_1.jsx)("div", { className: `relative ${className}`, children: (0, jsx_runtime_1.jsx)("div", { className: "w-24 h-24 bg-[#F23C34] border-4 border-black rounded-lg flex items-center justify-center shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-transform hover:scale-110", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Bot, { size: 48, strokeWidth: 2.5, color: "black" }) }) }));
exports.RoboticArmIcon = RoboticArmIcon;
const SecurityCameraIcon = ({ className }) => ((0, jsx_runtime_1.jsx)("div", { className: `relative ${className}`, children: (0, jsx_runtime_1.jsx)("div", { className: "w-24 h-24 bg-[#3061FF] border-4 border-black rounded-full flex items-center justify-center shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-transform hover:scale-110", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Cctv, { size: 48, strokeWidth: 2.5, color: "black" }) }) }));
exports.SecurityCameraIcon = SecurityCameraIcon;
